backend:
  name: git-gateway
  branch: main
  squash_merges: true

publish_mode: editorial_workflow
show_preview_links: true

media_folder: 'src/_assets/img'
public_folder: '/assets/img'

site_url: 'https://gwumtl.com'

i18n:
  structure: multiple_folders
  locales: [en, fr]

collections:
  - label: 'Global Data'
    name: data
    editor:
      preview: false
    delete: false
    files:
      - label: 'Site Info'
        name: siteinfo
        file: 'src/_data/siteinfo.yaml'
        fields:
          - { name: title, widget: string }
          - { name: url, widget: string }
  
  - label: 'Language Data'
    name: i18n
    folder: 'src/_i18n'
    extension: yaml
    editor:
      preview: false
    delete: false
    i18n:
      structure: multiple_files
    fields:
      - { name: title, widget: hidden }
      - label: 'Localized strings'
        label_singular: 'string'
        name: data
        widget: list
        summary: '{{fields.key}}: {{fields.t}}'
        create: true
        i18n: true
        fields:
          - { label: 'Key', name: key, widget: string }
          - { label: 'Translation', name: t, widget: string }

  - label: 'Pages'
    name: pages
    folder: 'src'
    extension: md
    identifier-field: name
    create: true
    delete: false
    i18n: true
    fields:
      - { label: 'Page name', name: name, widget: string, i18n: duplicate }
      - { label: 'Content', name: body, widget: markdown, modes: [raw], i18n: true }
